# information in properties
name="CompInStreent"
version="slV1.3"
package="com.kkz.compinstreent"
main="Java"
creator="bluesky"
description="Você consegue companhia, feito em Goiânia dia 8/04/26 ele foi criado, Goiânia, Goiás, Brasil."
